const fs = require('fs');

const page = '<?php\r\n\r\nnamespace App\\Filament\\Pages;\r\n\r\nuse Filament\\Pages\\Page;\r\nuse App\\Filament\\Widgets\\IntelligenceOverview;\r\nuse App\\Filament\\Widgets\\StrategyEfficiencyTable;\r\nuse App\\Filament\\Widgets\\HierarchyPerformanceTable;\r\n\r\nclass InformationLog extends Page\r\n{\r\n    protected static ?string $navigationIcon = "heroicon-o-presentation-chart-bar";\r\n\r\n    protected static string $view = "filament.pages.information-log";\r\n\r\n    public static function getNavigationGroup(): ?string\r\n    {\r\n        return __("Awareness Management");\r\n    }\r\n\r\n    public static function getNavigationLabel(): string\r\n    {\r\n        return __("Information Log");\r\n    }\r\n\r\n    public function getTitle(): string\r\n    {\r\n        return __("Information Log Intelligence");\r\n    }\r\n\r\n    public static function canAccess(): bool\r\n    {\r\n        $user = auth()->user();\r\n        return $user && $user->hasAnyRole(["super_admin", "admin", "woreda_coordinator", "paramilitary"]);\r\n    }\r\n\r\n    protected function getHeaderWidgets(): array\r\n    {\r\n        return [\r\n            IntelligenceOverview::class,\r\n        ];\r\n    }\r\n\r\n    protected function getFooterWidgets(): array\r\n    {\r\n        return [\r\n            StrategyEfficiencyTable::class,\r\n            HierarchyPerformanceTable::class,\r\n        ];\r\n    }\r\n}\r\n';

const chart = '<?php\r\n\r\nnamespace App\\Filament\\Widgets;\r\n\r\nuse App\\Models\\AwarenessEngagement;\r\nuse Filament\\Widgets\\ChartWidget;\r\nuse Illuminate\\Support\\Facades\\DB;\r\n\r\nclass StrategyEfficiencyChart extends ChartWidget\r\n{\r\n    protected static ?string $heading = "Strategy Efficiency (ውጤታማነት በስትራቴጂ)";\r\n    protected static ?int $sort = 2;\r\n\r\n    protected function getData(): array\r\n    {\r\n        $user = auth()->user();\r\n        \r\n        $query = AwarenessEngagement::query()->where("status", "approved");\r\n        \r\n        if ($user->hasRole("woreda_coordinator")) {\r\n            $query->where("woreda_id", $user->woreda_id);\r\n        } elseif ($user->hasRole("paramilitary")) {\r\n            $query->where("created_by", $user->id);\r\n        }\r\n\r\n        $data = (clone $query)\r\n            ->select("engagement_type", DB::raw("SUM(COALESCE(headcount, 0) + COALESCE(org_headcount_male, 0) + COALESCE(org_headcount_female, 0)) as total"))\r\n            ->groupBy("engagement_type")\r\n            ->pluck("total", "engagement_type")\r\n            ->toArray();\r\n\r\n        return [\r\n            "datasets" => [\r\n                [\r\n                    "label" => __("Reach by Strategy"),\r\n                    "data" => array_values($data),\r\n                    "backgroundColor" => ["#3b82f6", "#10b981", "#f59e0b", "#ef4444"],\r\n                ],\r\n            ],\r\n            "labels" => array_map(fn($k) => ucfirst(str_replace("_", " ", $k)), array_keys($data)),\r\n        ];\r\n    }\r\n\r\n    protected function getType(): string\r\n    {\r\n        return "pie";\r\n    }\r\n}\r\n';

fs.writeFileSync('app/Filament/Pages/InformationLog.php', page, 'utf8');
fs.writeFileSync('app/Filament/Widgets/StrategyEfficiencyChart.php', chart, 'utf8');
console.log('Final restoration complete.');
